### ISSUE TITLE
Copy Button

### ISSUE THREAD

**Issue by GabeRome** [ucsb-cs56-projects/cs56-music-beatbox#16]
create a button that copies the first four beats of the loop and sets them to the remaining 12 beats so you don't have to manually click in the same patterns over and over.
estimated 150

**Comment by mliou** [comment]
Approved.

**Comment by rhelmot** [comment]
W18 OK 100 points. I also approve an extra 100 points if the solution involves a clever and convenient interface for picking how much you want to copy and where.
