### ISSUE TITLE
Clean up Source Code

### ISSUE THREAD

**Issue by mastergberry** [ucsb-cs56-projects/cs56-music-beatbox#4]
~depends https://github.com/UCSB-CS56-Projects/cs56-music-beatbox/issues/3

This project seems really cool.  There are a few things that would make the code as cool as the idea is.  Take some time to improve on the GUI for the client to have a starting screen to select a server and port you wish to connect to.  This way the project is not reliant on CSIL and port 4242.

In the second GUI screen when interacting with the actual application there should be a menu drop down or a button somewhere to disconnect from the server which will lead them back to the initial screen so they can log in to a new server.

Remove the hardcoded server bindings (such as the port) and make it take parameters in from the command line to make the server application easier to deploy.

If possible split the client into smaller classes and add some Javadocs to them to make this code clean and perfect.

~Estimated 300 points

**Comment by rhelmot** [comment]
Duplicates of #5 #9
